### PR TITLE
New release 

### PR DESCRIPTION
**Pull request by mms29**
I changed the name MD-NMMD-GENESIS to MDTools to remove the hyphens, related to Pablo's comment. We need those changes in the master branch ASAP, as for now genesis won't build as it is searching for MD-NMMD-Genesis which no longer exists.

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
I will make you admin so you can merge your PRs without my reviews

**Comment by MohamadHarastani** [comment]
You need to update the release version before merging

**Comment by mms29** [comment]
> I will make you admin so you can merge your PRs without my reviews

Thanks 

> You need to update the release version before merging

Done

**Comment by mms29** [comment]
Don't look at the previous commit, I accidentally pushed some changes to devel. I reverted the changes. Now i just updated the version of continuosuflex

**Comment by MohamadHarastani** [comment]
Okay.. just for the sake of testing your admin rights, can you choose "merge without waiting for requirements to be met"? and merge this PR

**Pull request merged**
