### PR TITLE
LAPACK ARPACK in continuousflex-org + MD-NMMD-Genesis 2.0 +Fix pdb dim red viewer 

### PR DESCRIPTION
**Pull request by mms29**
**LAPACK ARPACK in continuousflex-org** 

I created a repo called continuousflex-lib with a new version of LAPACK (3.10.1) and the same version of ARPACK
The new lapack needs CMAKE 3.0 or higher (2014), not by default on CentOS 7 (you need to yum install cmake3 and do a symbolic link cmake->cmake3), by default on Ubuntu 18.0 and 20.0

Please try uninstalling all continuousflex (remove arpack, lapack, blas, lapacke from lib folder, remove content of tmp file, remove MD-NMMD-Genesis ) and reinstall and run all tests. I did it on my machines (Ubuntu 20.0, Ubuntu 18.0, Centos 7 ) 

**MD-NMMD-Genesis 2.0** 

New version of GENESIS (1.7.1, previously 1.4.0)

**Fix pdb dim red viewer** 

Bugs of saving trajectory and opening VMD

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
I tried the PDB viewer, and the animation works. I still have the problem in the animation of kind of sparse points instead of the full structure. In the PDB viewer file, can you add your name as an author to that file, it's better if questions are addressed to you there, its very far from where I left it.

**Comment by MohamadHarastani** [comment]
Hi @mms29 
I have recently switched to WSL and `cmake3` does not exist as a binary. What we can do, is check the CMake version, if it is not 3 or above, we will try to find `cmake3` binary on the system. If that is not there, we break the installation and give the user a message that they should install CMake version 3 or above. How about that?

I wrote a little script to check the version of CMake, I tested it on Centos and Ubuntu, it will give 2 or 3 depending on the system.
```
import subprocess
cmakeVersion = subprocess.Popen(["cmake",
                                 "--version"],
                                stdout=subprocess.PIPE
                                ).stdout.read().decode('utf-8').split(" ")[2][0]
print(cmakeVersion)
```
We don't want to upset Centos users as you know :-)

**Comment by mms29** [comment]
Hi Mohamad, sorry I left this PR for a while I was really busy. 

OK for CMAKE3 I will check the installed version.

For the error you have in the install, it is very strange, this error is due to the old version of LAPACK (dsyev is missing in the old version). But with the new version I uploaded in continuousflex-lib it should be fine. Are you sure you built the new LAPACK? can you check that it is the 3.10.1 ?
Otherwise, the problem might be that it detect first the LAPACK on your system instead of the one installed in Scipion. If so I'll need to work on that.

**Comment by mms29** [comment]
You can pull the changes and try installing. It should search for cmake3 if cmake is not version 3

**Comment by mms29** [comment]
I have the same error as you when building on an Australian supercomputer. I can not fix the problem for now, I just went back to an older version of GENESIS. Please pull and try and it should work.

**Comment by MohamadHarastani** [comment]
Hi @mms29 
I will test that today! 
Thanks man!

**Review by MohamadHarastani — APPROVED** [review]
I tested it, and everything went perfectly!
I would like to release this one since there isn't much development going on. If you have anything to add let me know.

**Pull request merged**
