### PR TITLE
Mh prerelease

### PR DESCRIPTION
**Pull request by MohamadHarastani**
This has a clean up and update of citations.
There are many "Help" that are missing for each protocol.
I will open an issue for adding the help for each protocol and variable in the protocols. 
A clean up is necessary as we move on since there are too many mistakes that will become difficult to clean.

Cheers

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
There is no need to make an extensive review, but I would like to merge this PR and release.

Here is the short way:
```
git pull
git checkout mh_prerelease 
scipion3 uninstallp -p scipion-em-continuousflex
scipion3 installp -p . --devel
scipion3 tests --grep continuousflex --run
```
You will notice one tests in xmipp that will fail since I corrected a typo in the file name, I will fix that later in xmipp, here there is nothing wrong.

Cheers

**Review by mms29 — APPROVED** [review]
I went rapidly over it, that's a great work thanks!

**Comment by mms29** [comment]
I will start working on the help messages for my protocols

**Comment by MohamadHarastani** [comment]
Thanks 😊

**Review by ilyes-hm — APPROVED** [review]

**Pull request merged**
