### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by MohamadHarastani**

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
@mms29 I tested the installation on a new computer and it worked like a charm.
I cannot test since Xmipp deprecated some programs. Xmipp master doesn't compile for me, so I will try to recover the deprecated programs and test again.
In the meantime, if you have anything to add its the time.

**Comment by MohamadHarastani** [comment]
Something is a little too verbose during the tests
```
> Reading pdb file /mnt/data1/shared/scipion3/data/tests/nma_V2.0/genesis/1ake.pdb ...
	 Done 

> Reading pdb file Runs/000669_FlexProtGenesis/extra/inputPDB_000001.pdb ...
	 Done 

> Reading pdb file Runs/000669_FlexProtGenesis/extra/output_000001_remd1.pdb ...
	 Done 

> Reading pdb file Runs/000669_FlexProtGenesis/extra/output_000001_remd2.pdb ...
	 Done 

> Matching PDBs atoms ...
Chains list 1  : ['A']
Chains list 1  : ['A']
Number of match : 1
Seg list 1  : ['P0']
Seg list 1  : ['P0']
Number of match : 0
	 Matching chains 1 ... 
	 211 matching atoms 
	 Done
> Aligning PDB ...
	 Done 

> Aligning PDB ...
	 Done 

> Aligning PDB ...
	 Done 
```

**Comment by MohamadHarastani** [comment]
I recovered the deprecated files in Xmipp, you can checkout this branch and run it.
https://github.com/I2PC/xmipp/pull/707

Something like this
```
./xmipp get_devel_sources devel
git checkout mh_undeprecate
scipion3 run ./xmipp
```

**Comment by MohamadHarastani** [comment]
All tests work for me! It's time to release :-)

**Comment by mms29** [comment]
Perfect let's go ! Can you deal with the release ? I am currently in
conference in Lorne until Thursday
Cheers

Le sam. 4 févr. 2023 à 05:49, MohamadHarastani ***@***.***> a
écrit :

**Comment by MohamadHarastani** [comment]
Done! Enjoy the conference.

**Pull request merged**
