### PR TITLE
Back to lapack 3.5.0 due to compilation errors with NMA code

### PR DESCRIPTION
**Pull request by mms29**

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
Thanks Remi for the fix. I am facing a very strange error on Ubuntu 18 in installing genesis. Aside from the NMA binaries, I think the other binaries should be made optional (genesis, deeplearning and optical flow). The three are difficult to install, and it might not be necessary to install them for any user at the installation level. The last two packages are cuda dependent, and will fail for users with no cuda on their system. What do you think?

**Review by MohamadHarastani — APPROVED** [review]

**Comment by mms29** [comment]
Hi Mohamad,

I think optional is the best. It looks like whatever you do, therer will
always be a system were the install will fail.
Even for the stupid arpack and lapack librairies, they are built by default
on many systems we shouldn't need to build them from source...
Please can you share the genesis error ?

Rémi

Le jeu. 10 nov. 2022 à 00:21, MohamadHarastani ***@***.***> a
écrit :

**Comment by MohamadHarastani** [comment]
Hi Remi
Here is the error that I got while compiling Gnesis. It has to do with openmpi version on Ubuntu18 or something.
The only problem in making all these libraries optional that without binaries non of the methods work. The lapack arpack compilation is inevitable. I wonder if lapack, arpack, blas can be installed using conda instead of the way it is now! 
```
config.status: src/config.h is unchanged
config.status: executing depfiles commands
Making install in src
make[1]: Entering directory '/home/harastam/scipion3/software/em/MD-NMMD-Genesis-1.1/src'
Making install in lib
make[2]: Entering directory '/home/harastam/scipion3/software/em/MD-NMMD-Genesis-1.1/src/lib'
cpp -traditional-cpp -traditional -DHAVE_CONFIG_H constants.fpp constants.f90
mpif90  -I. -I../../src  -I. -O3 -ffast-math -march=native -ffree-line-length-none -fopenmp  -c constants.f90
constants.fpp:18:6:

   use mpi
      1
Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
Makefile:698: recipe for target 'constants.o' failed
make[2]: *** [constants.o] Error 1
make[2]: Leaving directory '/home/harastam/scipion3/software/em/MD-NMMD-Genesis-1.1/src/lib'
Makefile:358: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/harastam/scipion3/software/em/MD-NMMD-Genesis-1.1/src'
Makefile:353: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
target '/home/harastam/scipion3/software/em/MD-NMMD-Genesis-1.1/bin/atdyn' not built (after running 'git clone -b merge_genesis_1.4 https://github.com/continuousflex-org/MD-NMMD-Genesis.git . ; autoreconf -fi ;./configure LDFLAGS=-L/home/harastam/scipion3/software/lib ;make install;')
```

**Comment by MohamadHarastani** [comment]
Actually they all can be installed as conda packages (lapack, arpack, blas). I asked Pablo to show me how we can have our own conda environment, I will focus on that first and we will come back to see what can be done to not having to compile lapack and arpack the way it is now.

**Comment by MohamadHarastani** [comment]
Update: I managed to create a conda environment and install lapack and arpack on it.
https://github.com/scipion-em/scipion-em-continuousflex/tree/mh_conda
NMA binaries compile well, even genesis compiles (until I get the same error that I was getting before). The deep learning and optical flow libraries install well too.
TestHEMNMA works. But the other tests (tomoflow and deepHEMNMA) will fail. I will work more on making TomoFlow works and let Ilyes do that for DeepHEMNMA.
We are finally a step towards resolving the conflicts and not having to install lapack and arpack manually!
Cheers

**Comment by MohamadHarastani** [comment]
This PR becomes obsolete if we install lapack and arpack using conda

**Comment by mms29** [comment]
The conda install is a great idea, it will simplify everything a lot!
For the GENESIS error, it can not find openmpi library in your LD_LIBRARY_PATH it might be that you do not have installed the devel package openmpi-dev but just openmpi, can you check ?

**Comment by mms29** [comment]
Sorry I misread the error,
It is just that the version of gfortran to build GENESIS and openmpi are not the same. You have to use the same version of gcc. It is most likely gcc 8.X that is used to build openmpi, make sure that your mpif90 uses gcc 8.X (mpif90 --version)

**Comment by MohamadHarastani** [comment]
Hi Remi
I don't know why there is version problems and I donno how to solve it. 
Here is what I have on my computer now:
```
(base) harastam@pc4-0002-a:~/scipion3/scipion-em-continuousflex$ mpif90 --version
GNU Fortran (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) harastam@pc4-0002-a:~/scipion3/scipion-em-continuousflex$ gcc --version
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) harastam@pc4-0002-a:~/scipion3/scipion-em-continuousflex$ gfortran --version
GNU Fortran (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) harastam@pc4-0002-a:~/scipion3/scipion-em-continuousflex$ mpirun --version
mpirun (Open MPI) 2.1.1

Report bugs to http://www.open-mpi.org/community/help/
(base) harastam@pc4-0002-a:~/scipion3/scipion-em-continuousflex$ 
```

**Comment by mms29** [comment]
I believe your openMPI version is quite old, I have version 4.0.3
What you can do is to locate your mpi.mod file and do 
`zcat /usr/lib/x86_64-linux-gnu/fortran/gfortran-mod-15/openmpi/mpi.mod | head`
for me it gives : 
`GFORTRAN module version '15' created from mpi-ignore-tkr.F90`

You can refer to this table to see which version corresponds to gcc version
```
GCC version    module file version
-----------------------------------
up to 4.3.2    unversioned
4.4            0
4.5.1          4
4.6.3          6
4.7.0pre       8
4.7.1          9
4.8.[1-3]      10
4.9.2          12
5.1.0          14
8.1.0          15 
9              15
10             15
11             15
```

I believe openMPI 2.X might use gcc 4.9.2, if so you will have to either ugrade openmpi or use the corresponding version of gcc

**Comment by MohamadHarastani** [comment]
I have `GFORTRAN module version '14' created from mpi-ignore-tkr.F90`
I will try to update my openmpi. I have version  2.1.1
I am running on Ubuntu 18, and for some reason, this is what appears up to date for me. I will try and let you know.

**Comment by mms29** [comment]
If you can not update openmpi on Ubuntu 18, you can just switch to gcc 5.1.0 for compiling

**Comment by MohamadHarastani** [comment]
Hmmm.. Thanks man. What puzzles me is how gcc and openmpi on Ubuntu 18 are not compatible!
I think this PR is now obsolete since the conda environment will install lapack, arpack etc.

**Comment by mms29** [comment]
I know so stupid right ... Could you compile by changing gcc version ?

**Pull request closed without merging**
