### PR TITLE
Yun refact

### PR DESCRIPTION
**Pull request by pconesa**
I'm trying to tidy up branches here. Please let me know if my assumptions ar wrong.

Main development branch y "devel" ....most of the branches started from devel and will be merged back to devel.

### CODE REVIEW

**Comment by MohamadHarastani** [comment]
Hi @pconesa ,
Yes, your assumptions are correct.
The master branch is still the version of Scipion2, and we better keep it this way until Scipion3 is officially released.
The devel branch is as you say (we can back it up on slajo/).
I imported this branch (yun_refact) to test the plugin and I found that there is a bug in the StructMap protocol ([link](https://www.evernote.com/shard/s648/sh/b8facb37-7096-b0a9-4626-ac9bfc5740e1/57c4579b130ed3af749cf8d370378210) to reproduce) I discussed it with @fonsecareyna82 last Friday. I don't know if Yunior had the time to look at it (plz see if he did anything before you attack it).
We can use this branch to fix this bug, once solved we can merge and remove all the other branches.

**Comment by pconesa** [comment]
Thanks, @MohamadHarastani .What are those files .py to download....is that needed? can't they be in the plugin?

**Comment by MohamadHarastani** [comment]
> Thanks, @MohamadHarastani .What are those files .py to download....is that needed? can't they be in the plugin?

Thanks for asking, I need some help again here. But I am opening the issues one at a time.
About these *.py files, some of them are imported from another package called "mode hunter", and some of them are written based on this package.
Here is an [example](https://github.com/scipion-em/scipion-em-continuousflex/blob/devel/continuousflex/protocols/protocol_nma_base.py#L164
) of how they are used inside the plugin.
They are made to be called as executables, and this makes it easy to call them from anywhere (bash, C++, ...)
I recently migrated them to Python3 (see [this](https://github.com/MohamadHarastani/nma_python_binaries/tree/python3_version) branch)
The first line of each of these files, they will look for the python3 that is in your path (#!/usr/bin/env python3) to execute (see [example](https://github.com/MohamadHarastani/nma_python_binaries/blob/python3_version/nma_animate_pseudoatoms.py#L1))
They only need numpy to be installed on they python3 that is in your path, which is already taken care of during scipion3 installation (I saw that python3-numpy is scipion3 dependency).
All seems fine except of one problem:
If you install Scipion3 with conda, these files work properly.
If you install it with venv, it is causing a problem of not finding python3 in the path (overwritten by the virtual environment perhaps).
Do you know a way to workaround this problem? Do you think it's safe (works on any system) to explicitly assume that python3 is in this path (#!/usr/bin/python3)?

**Comment by pconesa** [comment]
Yes this is an issue since depending on the environment and even de OS (you might have "python" or "python3"). We know that under our environemnt (conda or virtualenv) you'll will always have "python". So better have python in the first line. We are also running scripts with "python path/to/python/script.py" that will avoid having script.py with +x permission, something lost when you package your python code into a pip package.

**Comment by pconesa** [comment]
@MohamadHarastani this fixes several things. Can we merge this and focus then in your issue?

**Comment by MohamadHarastani** [comment]
> @MohamadHarastani this fixes several things. Can we merge this and focus then in your issue?

Sure!

**Comment by MohamadHarastani** [comment]
> Yes this is an issue since depending on the environment and even de OS (you might have "python" or "python3"). We know that under our environemnt (conda or virtualenv) you'll will always have "python". So better have python in the first line. We are also running scripts with "python path/to/python/script.py" that will avoid having script.py with +x permission, something lost when you package your python code into a pip package.

Thanks a lot for this explanation. Now its much more clear to me. I will first try to use python instead of python3. If this fails, I might consider if future to rewrite the calls to be "python path/to/python/script.py".

**Pull request merged**
