### PR TITLE
DeepHEMNMA

### PR DESCRIPTION
**Pull request by ilyes-hm**

### CODE REVIEW

**Review by mms29 — COMMENTED** [review]
Concerning your code, I assume your changes are correct, you know your code better than me.

However, I ran your test on my system but it failed, any ideas ?
```
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000002_ProtImportPdb/logs/run.db" 2'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000040_FlexProtNMA/logs/run.db" 40'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000088_ProtImportParticles/logs/run.db" 88'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000162_XmippProtCropResizeParticles/logs/run.db" 162'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000226_ProtSubSet/logs/run.db" 226'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000285_ProtSubSet/logs/run.db" 285'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000344_FlexProtAlignmentNMA/logs/run.db" 344'
** Running command: 'python3 /home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/disk1/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000403_FlexProtDeepHEMNMATrain/logs/run.db" 403'

*************** last 50 lines of STD OUT *********************

Logging configured. STDOUT --> Runs/000403_FlexProtDeepHEMNMATrain/logs/run.stdout , STDERR --> Runs/000403_FlexProtDeepHEMNMATrain/logs/run.stderr
RUNNING PROTOCOL -----------------
Protocol starts
Hostname: Box1
PID: 2336457
pyworkflow: 3.0.22
plugin: continuousflex
plugin v: 3.1.4
currentDir: /media/disk1/ScipionUserData/projects/TestDeepHEMNMA1
workingDir: Runs/000403_FlexProtDeepHEMNMATrain
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: performDeepHEMNMAStep, step 1, time 2022-08-22 13:47:05.092800
Protocol failed: Command 'python /home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.
FAILED: performDeepHEMNMAStep, step 1, time 2022-08-22 13:47:06.640051
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 1/2)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

Traceback (most recent call last):
  File "/home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py", line 10, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
    resultFiles = self._runFunc()
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
    return self._func(*self._args)
  File "/home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/protocols/protocol_deep_hemnma_train.py", line 103, in performDeepHEMNMAStep
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=None, cwd=None)
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python /home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.
Protocol failed: Command 'python /home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.

*************** end of STD ERR *********************

[   FAILED ] TestDeepHEMNMA1.test_HEMNMA_atomic

Traceback (most recent call last):
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/remi/continuousflex_dir_scipion3/scipion-em-continuousflex/continuousflex/tests/test_workflow_Deep_HEMNMA.py", line 110, in test_HEMNMA_atomic
    self.launchProtocol(protTrain)
  File "/home/remi/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 113, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol continuousflex - deep hemnma train execution failed. See last log lines above for more details.

[==========] run 1 tests (39.106 secs)
[  FAILED  ] 1 tests
[  PASSED  ] 0 tests

```

**Comment by ilyes-hm** [comment]
There is a problem with the tensorboard library, it may come from protobuf or tensorboard can you make sure that they are both installed

**Comment by mms29** [comment]
Both are installed : 
```
scipion3 run pip list | grep "tensorboard\|protobuf"
protobuf                  4.21.5
tensorboard               2.8.0
tensorboard-data-server   0.6.1
tensorboard-plugin-wit    1.8.1
```
I launched on my laptop and I have the same error

**Comment by ilyes-hm** [comment]
try to downgrade the protobuf package to 3.20.x or lower, for me I have 3.20.0

**Comment by mms29** [comment]
I upgraded protobuf I have the same error
Here is my full env 
```
scipion3 run pip list 
Scipion v3.0.10 - Eugenius
** Running command:  pip "list"
Package                   Version   Location
------------------------- --------- ---------------------------------------------------
absl-py                   1.2.0
appdirs                   1.4.4
autograd                  1.4
bibtexparser              1.2.0
biopython                 1.76
cachetools                5.2.0
certifi                   2021.10.8
chardet                   4.0.0
configparser              5.0.2
cycler                    0.11.0
decorator                 5.1.1
emtable                   0.0.10
farneback3d               0.1.3
future                    0.18.2
google-auth               2.11.0
google-auth-oauthlib      0.4.6
grpcio                    1.47.0
idna                      2.10
imageio                   2.19.0
importlib-metadata        4.12.0
joblib                    1.1.0
kiwisolver                1.4.2
littleutils               0.2.2
llvmlite                  0.38.1
Mako                      1.2.0
Markdown                  3.4.1
MarkupSafe                2.1.1
matplotlib                3.2.2
mpi4py                    3.0.3
mrcfile                   1.3.0
networkx                  2.8
numba                     0.55.2
numpy                     1.18.4
oauthlib                  3.2.0
opencv-python             4.6.0.66
outdated                  0.2.0
packaging                 21.3
peppercorn                0.6
Pillow                    8.2.0
pip                       21.2.4
platformdirs              2.5.2
plotter                   1.3.19
ProDy                     2.2.0
protobuf                  3.20.0
psutil                    5.8.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pycuda                    2020.1
pynndescent               0.5.7
pyparsing                 3.0.8
python-dateutil           2.8.2
pytools                   2022.1.7
pytz                      2022.1
PyWavelets                1.3.0
requests                  2.25.1
requests-oauthlib         1.3.1
rsa                       4.9
scikit-image              0.19.2
scikit-learn              0.22.1
scipion-app               3.0.10
scipion-em                3.0.17    /home/guest/scipion-em
scipion-em-chimera        3.1.7
scipion-em-continuousflex 3.1.4     /home/guest/scipion-em-continuousflex
scipion-em-prody          3.2.0     /home/guest/scipion-em-prody
scipion-em-relion         4.0.3     /home/guest/scipion-em-relion
scipion-em-xmipp          22.4.0    /home/guest/xmipp-bundle/xmipp/src/scipion-em-xmipp
scipion-pyworkflow        3.0.21
scipy                     1.8.0
SCons                     4.3.0
setuptools                61.2.0
six                       1.16.0
tensorboard               2.8.0
tensorboard-data-server   0.6.1
tensorboard-plugin-wit    1.8.1
threadpoolctl             3.1.0
tifffile                  2021.11.2
tk-html-widgets           0.4.0
tkcolorpicker             2.1.3
torch                     1.10.1
torchvision               0.11.2
tqdm                      4.64.0
typing_extensions         4.2.0
umap                      0.1.1
umap-learn                0.5.3
urllib3                   1.26.9
Werkzeug                  2.2.2
wheel                     0.37.1
zipp                      3.8.1

```

**Comment by mms29** [comment]
It works but then there is a new error : 

```
scipion3 test continuousflex.tests.test_workflow_Deep_HEMNMA
Scipion v3.0.10 - Eugenius
Running tests....
Creating project at:  /home/guest/ScipionUserData/projects/TestDeepHEMNMA1/project.sqlite
>>>> python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download nma_V2.0  -u https://raw.githubusercontent.com/continuousflex-org/testdata-continuousflex/main
Selected datasets: nma_V2.0
Local copy of dataset nma_V2.0 detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000002_ProtImportPdb/logs/run.db" 2'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000040_FlexProtNMA/logs/run.db" 40'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000088_ProtImportParticles/logs/run.db" 88'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000162_XmippProtCropResizeParticles/logs/run.db" 162'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000226_ProtSubSet/logs/run.db" 226'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000285_ProtSubSet/logs/run.db" 285'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000344_FlexProtAlignmentNMA/logs/run.db" 344'
** Running command: 'python3 /home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/guest/ScipionUserData/projects/TestDeepHEMNMA1" "Runs/000403_FlexProtDeepHEMNMATrain/logs/run.db" 403'

*************** last 50 lines of STD OUT *********************

Logging configured. STDOUT --> Runs/000403_FlexProtDeepHEMNMATrain/logs/run.stdout , STDERR --> Runs/000403_FlexProtDeepHEMNMATrain/logs/run.stderr
RUNNING PROTOCOL -----------------
Protocol starts
Hostname: guest-Precision-7550
PID: 23082
pyworkflow: 3.0.21
plugin: continuousflex
plugin v: 3.1.4
currentDir: /home/guest/ScipionUserData/projects/TestDeepHEMNMA1
workingDir: Runs/000403_FlexProtDeepHEMNMATrain
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: performDeepHEMNMAStep, step 1, time 2022-08-25 09:23:03.242797
****************************************************
Runs/000403_FlexProtDeepHEMNMATrain/extra
****************************************************
the train set size is: 2 images
the validation set size is: 1 images
torch.Size([3])
torch.Size([4])
torch.Size([2])
torch.Size([3])
torch.Size([4])
torch.Size([2])
torch.Size([3])
torch.Size([4])
torch.Size([2])
torch.Size([3])
torch.Size([4])
torch.Size([2])
epoch [1/400], loss:0.4469
torch.Size([3])
torch.Size([4])
torch.Size([2])
Protocol failed: Command 'python /home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.
FAILED: performDeepHEMNMAStep, step 1, time 2022-08-25 09:23:07.663348
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 1/2)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

  amplitudes = torch.tensor(amplitudes)
/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/data/cryoem_data.py:99: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  angles = torch.tensor(angles)
/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/data/cryoem_data.py:101: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  shifts = torch.tensor(shifts)
Traceback (most recent call last):
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py", line 99, in <module>
    train(sys.argv[1],
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py", line 87, in train
    pred_params = model(img.to(DEVICE), 'validation')
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/models/deep_hemnma.py", line 29, in forward
    resnet = self.resnet(x)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/models/resnet.py", line 238, in forward
    return self._forward_impl(x)
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/models/resnet.py", line 231, in _forward_impl
    x = self.layer4(x)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/processing_dh/models/resnet.py", line 60, in forward
    out = self.bn1(out)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/torch/nn/functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])
Traceback (most recent call last):
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
    resultFiles = self._runFunc()
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
    return self._func(*self._args)
  File "/home/guest/scipion-em-continuousflex/continuousflex/protocols/protocol_deep_hemnma_train.py", line 103, in performDeepHEMNMAStep
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=None, cwd=None)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python /home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.
Protocol failed: Command 'python /home/guest/scipion-em-continuousflex/continuousflex/protocols/utilities/deep_hemnma.py Runs/000344_FlexProtAlignmentNMA/extra/images.xmd Runs/000403_FlexProtDeepHEMNMATrain/extra 400 2 0.000100 3 0' returned non-zero exit status 1.

*************** end of STD ERR *********************

[   FAILED ] TestDeepHEMNMA1.test_HEMNMA_atomic

Traceback (most recent call last):
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/guest/scipion-em-continuousflex/continuousflex/tests/test_workflow_Deep_HEMNMA.py", line 110, in test_HEMNMA_atomic
    self.launchProtocol(protTrain)
  File "/home/guest/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 113, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol continuousflex - deep hemnma train execution failed. See last log lines above for more details.

[==========] run 1 tests (27.206 secs)
[  FAILED  ] 1 tests
[  PASSED  ] 0 tests
```

**Comment by ilyes-hm** [comment]
try to pull the changes and test it now

**Comment by mms29** [comment]
All test passed! 
One last thing, you need to find a way to do export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python automatically
I don't how you use you program exactly, if it is an external program that you call using runCommand/runJob/os.system, you need to specify an environment with this variable inside

**Comment by ilyes-hm** [comment]
I can add that, however I believe this is not a general problem because I already tested it with different machines and it worked fine without the PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

**Comment by mms29** [comment]
It was needed on both my laptop and my system in the lab (both Ubuntu)
What is changing when declaring this variable ? If there is no regression you can add it just in case.
Otherwise we need to understand why the error occurred and find an other way to solve it. ( Does it depends on a library ? which linux distro ? etc)

**Comment by ilyes-hm** [comment]
actually it is a bit slower when PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python is used instead of CPP, it is related to the protobuf library that is used by tensorboard for visualization, if it happened to you with two machines then it makes sense to add it

**Comment by mms29** [comment]
Does it slow up the visualization only ? Or the protocol ? If so it might not be the best if it can be avoided

Also, can you update the README.md file and add a description of your method, some notes if needed, in the fashion we did for the other methods, then pull your changes

**Comment by ilyes-hm** [comment]
It slows the protocol that's why I did not add it, and the readme is up to date from my side

**Comment by MohamadHarastani** [comment]
I tested this branch on two systems: Ubuntu and WSL Ubuntu, and the test passed without the flag that switches Cpp to Python.
I will approve this PR, and check all the tests on the devel branch after starting clean.. if the problem resurfaces, we will figure out a solution.

**Review by MohamadHarastani — APPROVED** [review]

**Pull request merged**
